### ISSUE TITLE
deceleration/acceleration factor

### ISSUE THREAD

**Issue by julianher** [kiwicampus/2D-Test-Track-Service-Desk-Project#2]
Hi!

I have a doubt. The ratio of acceleration and deceleration corresponds to the ratio of time it takes to accelerate or decelerate? For example, for a ratio of 1/4 would be 1/4*time acceleration, 2/4*time constant and 1/4*time deceleration.

Thanks.

**Comment by camilopq97** [comment]
Yes, that's exactly what it means.
